env                   = deployment
# liquibaseTaskPrefix   = liquibase
# db.url              = jdbc:postgresql://host.docker.internal:5454/kappi
# db.user             = postgres
# db.password         = postgres
org.gradle.jvmargs    = -Xmx1024M
kotlin.daemon.jvmargs = -Xmx2048M
org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers
