##################################################################################################################
# The included Docker Compose file defines the infrastructure services required for the Ragu applications.
# It ensures that the PostgreSQL containers are fully started before initiating the application build processes,
# as the applications depend on fully migrated databases for code generation from the database schema.
# Including this file allows us to manage the containers through a single Docker Compose file once the initial
# setup is completed and allows us to leverage `depends_on` directive to ensure the correct startup order.
# Running the initial setup from this file will result in error because `ragu-chat-api` will not be able to connect
# to the `ragu-chat-api-postgres` service.
#################################################################################################################
include:
  - "docker-compose-infra.yaml"
name: ragu
services:
  ragu-chat-api:
    build:
      context: "ragu-chat-api"
      additional_contexts:
        config: "config/ragu-chat-api"
      dockerfile: "../docker/ragu-chat-api/Dockerfile"
    ports:
      - "42070:42069"
    depends_on:
      - "ragu-chat-api-postgres"
      - weaviate
  ragu-web-app:
    build:
      context: "ragu-web-app"
      additional_contexts:
        config: "config/ragu-web-app"
      dockerfile: "../docker/ragu-web-app/Dockerfile"
    ports:
        - "3000:3000"
  ragu-chunker:
    platform: "linux/amd64"
    build:
      context: "ragu-chunker"
      dockerfile: "docker/chonkit.Dockerfile"
    env_file:
      - "config/ragu-chunker/.env"
    depends_on:
      - "ragu-chunker-postgres"
      - weaviate
    ports:
      - "42069:42069"
    volumes:
      - "ragu_chunker_data:/var/lib/docker/ragu/data"

volumes:
  ragu_chunker_data: